"""Unit tests for the compact travel John composer."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(REPO_ROOT / "src"))

from bsb_pdf_toolkit.generate_travel_pdf import (  # noqa: E402
    FONT_MISSING_MESSAGE,
    GRID_PROOF_FAMILY,
    GRID_PROOF_FONT_MISSING_MESSAGE,
    GRID_PROOF_WATERMARK,
    MILO_TEXT_FAMILY,
    PROTESTANT_CANON,
    SPEC,
    GridProofFontError,
    MiloFontError,
    classify_grid_proof_fonts,
    classify_milo_fonts,
    default_output_paths,
    infer_last_page_run_head,
    footnote_markup,
    generate_travel_typst,
    is_source_nav_marker,
    merge_travel_pdfs,
    is_hebrew_script,
    body_leading_gap_pt,
    book_part_slug,
    leading_gap_pt,
    main,
    measure_em,
    paragraph_markup,
    render_text_chunk,
    require_grid_proof_fonts,
    require_milo_fonts,
    select_travel_books,
    travel_preamble,
    verse_segments_travel,
    xref_markup,
)
from bsb_pdf_toolkit.generate_typst_pdf import (  # noqa: E402
    parse_usfm_zip,
    strip_osis_display_tails,
)

USFM_ZIP = REPO_ROOT / "drafts" / "primary" / "source" / "engbsb_usfm.zip"

SAMPLE_USFM = r"""
\id JHN Autogenerated BSB by bsb2usfm
\usfm 3.1
\h John
\toc1 The Gospel According to John
\mt1 John
\c 1
\s1 The Beginning
\r (\ref Genesis 1:1–2|GEN 1:1-2\ref*; \ref Hebrews 11:1–3|HEB 11:1-3\ref*)
\p \v 1 In the beginning was the Word, and the Word was with God, and the Word was God. \v 2 He was with God in the beginning.
\s1 The First Disciples
\p \v 38 Jesus turned and saw them following. \wj “What do you want?”\wj* He asked.
\p \wj \v 39 “Come and see,”\wj* He replied.
\p \v 16 \wj For God so loved the world that He gave His one and only\f + \fr 3:16 \ft Or \ft only begotten \ft or \fqa unique\ft ; also in verse 18\f* Son.\wj*
\c 2
\s1 The Wedding at Cana
\p \v 1 On the third day a wedding took place at Cana in Galilee.
\pc JESUS OF NAZARETH, THE KING OF THE JEWS.
""".strip()


SAMPLE_PSA = r"""
\id PSA Autogenerated BSB by bsb2usfm
\h Psalm
\toc1 Psalm
\c 1
\ms BOOK I
\d Psalms 1–41
\q1 \v 1 Blessed is the man who does not walk.
\c 3
\d \v 1 A Psalm of David, when he fled from his son Absalom.
\q1 O LORD, how my foes have increased!
\qr Selah
\c 118
\q1 \v 29 Give thanks to the LORD, for He is good.
\c 119
\s1 Your Word Is a Lamp to My Feet
\qa ALEPH
\q1 \v 1 Blessed are those whose way is blameless.
""".strip()


def write_sample_zip(path: Path) -> Path:
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("bsb_usfm/JHN.usfm", SAMPLE_USFM)
        zf.writestr("bsb_usfm/GEN.usfm", "\\id GEN\n\\h Genesis\n\\c 1\n\\p \\v 1 In the beginning.\n")
        zf.writestr("bsb_usfm/PSA.usfm", SAMPLE_PSA)
    return path


def test_spec_line_matches_page():
    text_block_in = SPEC.lines_per_page * SPEC.baseline_pt / 72.0
    assert SPEC.trim_width_in == 4.75
    assert SPEC.trim_height_in == 7.0
    assert SPEC.body_pt == 8.5
    assert SPEC.baseline_pt == 10.5
    assert SPEC.margin_inside_in + SPEC.margin_outside_in + SPEC.measure_in == pytest.approx(4.75)
    assert SPEC.margin_head_in + SPEC.margin_foot_in + text_block_in == pytest.approx(7.0)
    assert SPEC.target_cpl_min == 60
    assert SPEC.target_cpl_max == 70
    em = measure_em()
    assert 30 <= em <= 34
    assert leading_gap_pt() == 2.0
    assert SPEC.body_leading_extra_pt == 0.35
    assert body_leading_gap_pt() == pytest.approx(2.35)


def test_preamble_is_milo_text_not_a_substitute():
    preamble = travel_preamble()
    assert MILO_TEXT_FAMILY in preamble
    assert "MiloSerif-Text" in preamble
    assert "fallback: false" in preamble
    assert 'lang: "en"' in preamble
    assert "hyphenate: true" in preamble
    assert f"hyphenation: {SPEC.hyphenation_cost_pct}%" in preamble
    assert SPEC.hyphenation_cost_pct == 80
    assert "#let divine(" in preamble
    assert 'linebreaks: "optimized"' in preamble
    assert "overhang: true" in preamble
    assert "Source Serif" not in preamble or "Do not substitute Source Serif" in preamble
    assert "Lexend" not in preamble
    assert "WeasyPrint" not in preamble
    assert str(SPEC.woc_rgb[0]) in preamble


def test_require_milo_fonts_fails_closed_on_empty_dir(tmp_path):
    empty = tmp_path / "milo"
    empty.mkdir()
    with pytest.raises(MiloFontError) as exc:
        require_milo_fonts(empty)
    assert FONT_MISSING_MESSAGE in str(exc.value)


def test_require_milo_fonts_rejects_source_serif_substitute(tmp_path):
    font_dir = tmp_path / "milo"
    font_dir.mkdir()
    (font_dir / "SourceSerif4-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-It.otf").write_bytes(b"OTTO")
    found = classify_milo_fonts(font_dir)
    assert found["text"] == []
    with pytest.raises(MiloFontError) as exc:
        require_milo_fonts(font_dir)
    assert FONT_MISSING_MESSAGE in str(exc.value)


def test_require_milo_fonts_accepts_documented_names(tmp_path):
    font_dir = tmp_path / "milo"
    font_dir.mkdir()
    (font_dir / "MiloSerif-Text.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-TextItalic.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-Bold.otf").write_bytes(b"OTTO")
    found = require_milo_fonts(font_dir)
    assert len(found["text"]) == 1
    assert len(found["text-italic"]) == 1
    assert found["regular"]
    assert found["bold"]


def test_print_target_exits_2_without_fonts(tmp_path, capsys):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([str(usfm), str(pdf), "--typst-out", str(typ), "--font-dir", str(tmp_path / "missing")])
    assert code == 2
    err = capsys.readouterr().err
    assert FONT_MISSING_MESSAGE in err
    assert typ.exists()


def test_no_compile_writes_typst_without_fonts(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--no-compile",
    ])
    assert code == 0
    text = typ.read_text()
    assert "The Gospel According to John" in text
    assert "#woc[" in text
    assert "#footnote[" in text
    assert "#chapter-xrefs[" in text
    assert "#chapter-drop(" in text
    assert "Genesis 1:1" in text
    assert "#inscription[" in text
    assert "In the beginning was the Word" in text
    assert "Source Serif" not in text.split("Do not substitute Source Serif")[-1]


def test_parse_filters_to_john_only(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    books = parse_usfm_zip(usfm, book_names=["John"])
    assert [book["book"] for book in books] == ["John"]
    assert books[0]["title"] == "The Gospel According to John"


def test_words_of_christ_and_verse_inside_wj():
    segs = verse_segments_travel(
        r"\wj \v 39 “Come and see,”\wj* He replied.",
        "John",
        1,
    )
    assert segs[0][0] == 39
    assert "#woc[" in segs[0][2]
    assert "Come and see" in segs[0][2]
    assert "He replied" in segs[0][2]
    assert segs[0][2].index("#woc[") < segs[0][2].index("Come and see")


def test_words_of_christ_span_verses_same_paragraph():
    raw = (
        r'\v 5 Jesus answered, \wj “Truly, truly, I tell you. '
        r'\v 6 Flesh is born of flesh.”\wj*'
    )
    segs = verse_segments_travel(raw, "John", 3)
    assert segs[0][0] == 5
    assert segs[1][0] == 6
    assert "#woc[" in segs[0][2]
    assert "#woc[" in segs[1][2]
    assert "Flesh is born" in segs[1][2]


def test_footnote_inside_woc_keeps_note():
    raw = (
        r"\v 16 \wj For God so loved the world\f + \fr 3:16 \ft Or \fqa unique\f* Son.\wj*"
    )
    segs = verse_segments_travel(raw, "John", 3)
    body = segs[0][2]
    assert "#woc[" in body
    assert "#footnote[" in body
    assert "unique" in body


def test_xref_markup_strips_wrapping_parens():
    text = xref_markup(r"(\ref Genesis 1:1–2|GEN 1:1-2\ref*; \ref Hebrews 11:1–3|HEB 11:1-3\ref*)")
    assert text.startswith("#link(")
    assert "Genesis 1:1" in text
    assert not text.startswith("(")
    assert "|GEN" not in text
    assert "|HEB" not in text


def test_fqa_becomes_italic():
    markup = footnote_markup(r"+ \fr 1:5 \ft Or \fqa comprehended")
    assert "#emph[comprehended]" in markup


def test_strip_osis_display_tails_drops_book_slugs():
    assert strip_osis_display_tails("see 1 Chronicles 2:9–10|1CH 2:9-10") == "see 1 Chronicles 2:9–10"
    assert strip_osis_display_tails("Ruth 4:18–22|RUT 4:18-22") == "Ruth 4:18–22"
    assert strip_osis_display_tails("Isaiah 7:14|ISA 7:14") == "Isaiah 7:14"
    assert strip_osis_display_tails("plain text") == "plain text"


def test_footnote_markup_strips_osis_tail_after_fqa():
    markup = footnote_markup(
        r"+ \fr 1:3 \ft Greek \fqa Aram\ft , a variant of \fqa Ram\ft ; "
        r"also in verse 4; see \ref 1 Chronicles 2:9–10|1CH 2:9-10\ref*."
    )
    assert "#emph[Aram]" in markup
    assert "#emph[Ram]" in markup
    assert "1 Chronicles 2:9" in markup
    assert "#link(" in markup
    assert "|1CH" not in markup
    assert "1CH 2:9" not in markup
    assert "Aram]," in markup
    assert "#emph[Ram] ;" in markup


def test_footnote_markup_strips_bare_osis_slug():
    markup = footnote_markup(r"+ \fr 1:3 \ft see 1 Chronicles 2:9–10|1CH 2:9-10")
    assert "1 Chronicles 2:9" in markup
    assert "|1CH" not in markup


def test_infer_last_page_run_head_from_prev_leaf():
    last = (
        "MATTHEW · 1:1–9\n"
        "15So the guards took the money and did as they were instructed.\n"
        "16Meanwhile, the eleven disciples went to Galilee.\n"
        "19 Therefore go and make disciples of all nations,\n"
        "20 and teaching them to obey all that I have commanded you.\n"
        "1771\n"
    )
    assert infer_last_page_run_head("MATTHEW · 28:11–20", last) == "MATTHEW · 28:15–20"


def test_paragraph_markup_drops_next_source_marker():
    assert is_source_nav_marker("Next:")
    assert is_source_nav_marker("next:")
    assert not is_source_nav_marker("Next came the Magi.")
    assert paragraph_markup({"marker": "p", "raw": "Next:"}, "Matt", 1) == []
    kept = paragraph_markup({"marker": "p", "raw": r"\v 2 He was with God."}, "John", 1)
    assert kept and "He was with God" in kept[0]


def test_psalm_descriptive_title_with_verse_keeps_drop():
    para = {
        "marker": "d",
        "raw": r"\v 1 A Psalm of David, when he fled from his son Absalom.",
    }
    lines = paragraph_markup(para, "Ps", 3, chapter_open=True)
    assert any("#chapter-drop(" in line for line in lines)
    assert any("A Psalm of David" in line for line in lines)


def test_chapter_open_drop_uses_only_first_verse():
    para = {
        "marker": "p",
        "raw": r"\v 1 In the beginning was the Word. \v 2 He was with God.",
    }
    lines = paragraph_markup(para, "John", 1, chapter_open=True)
    assert any("#chapter-drop(" in line for line in lines)
    assert any("#verse(" in line and ", 1, 2)" in line for line in lines)


def test_verse_number_is_boxed_in_preamble():
    preamble = travel_preamble()
    assert "#box[#vnum(n)#h(0.12em)]" in preamble
    assert "place(center + horizon)" in preamble


def test_preamble_defines_chapter_state_before_page_header():
    preamble = travel_preamble()
    assert preamble.index('#let chapter-label = state("chapter-label"') < preamble.index("#set page(")
    assert preamble.index("#let mark-run(label)") < preamble.index("#set page(")
    assert preamble.index("#let format-run-head(") < preamble.index("#set page(")
    assert "query(<run-head>)" in preamble
    assert "query(<run-verse>)" in preamble
    assert "[#metadata((ch, n))<run-verse>]" in preamble
    assert "verse(url, n, verse-n, body)" in preamble
    assert 'book + " · " + str(start-ch) + ":" + str(start-v) + "–" + str(end-v)' in preamble
    grid = travel_preamble(grid_proof=True)
    assert "query(<run-verse>)" in grid
    assert 'align(if even { left } else { right }, header)' not in grid
    assert "align(right, label)" in grid
    assert "align(left, label)" in grid


def test_preamble_resets_footnote_letters_in_page_header():
    preamble = travel_preamble()
    header_at = preamble.index("header: context")
    footer_at = preamble.index("footer: context")
    reset_at = preamble.index("counter(footnote).update(0)", header_at)
    assert reset_at < footer_at
    assert '#set footnote(numbering: "a")' in preamble
    assert "starts at \"a\" again" in preamble
    grid = travel_preamble(grid_proof=True)
    assert grid.index("counter(footnote).update(0)", grid.index("header: context")) < grid.index(
        "footer: context"
    )


def test_generate_travel_typst_john_sample(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "john.typ"
    books = generate_travel_typst(usfm, out, books=("John",))
    text = out.read_text()
    assert books[0]["book"] == "John"
    assert text.count("#book-title") == 1
    assert "Genesis" not in text or "Genesis 1:1" in text
    assert "In the beginning." not in text
    assert "#set page(" in text
    assert "4.75in" in text or "4.75" in text
    assert '#outline-book("John")' in text
    assert "#outline-chapter(1)" in text
    assert "#outline-chapter(2)" in text
    assert "#keep-with[" in text
    assert text.index("#keep-with[") < text.index('#section("The Beginning")')
    assert text.index('#section("The Beginning")') < text.index("#outline-chapter(1)")
    assert text.index("#outline-chapter(1)") < text.index("In the beginning was the Word")
    assert "Berean Standard Bible" not in text
    assert "Travel print sample" not in text


def test_psalm_lamp_title_breaks_from_prior_psalm_and_keeps_aleph(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "psalm.typ"
    generate_travel_typst(usfm, out, books=("Psalms",), grid_proof=True)
    text = out.read_text(encoding="utf-8")
    lamp = text.index('#section("Your Word Is a Lamp to My Feet")')
    aleph = text.index('#stanza("ALEPH")')
    drop = text.index("#chapter-drop(", text.find('#mark-run("PSALM · 119")'))
    keep = text.rfind("#keep-with-break[", 0, lamp)
    assert keep != -1
    assert keep < lamp < aleph < drop
    assert text.find("]", drop) > drop
    assert "#keep-with-break[" in text
    assert text.index("Give thanks to the LORD") < keep


@pytest.mark.skipif(not USFM_ZIP.exists(), reason="official BSB USFM zip not present")
def test_real_usfm_john_preserves_corpus_text(tmp_path):
    out = tmp_path / "john.typ"
    books = generate_travel_typst(USFM_ZIP, out, books=("John",))
    assert [book["book"] for book in books] == ["John"]
    assert len(books[0]["chapters"]) == 21
    text = out.read_text(encoding="utf-8")
    assert "For God so loved the world" in text
    assert "In the beginning was the Word" in text
    assert "#woc[" in text
    assert text.count("#chapter-drop(") == 21
    assert "Source Serif 4" not in text
    assert "Lexend" not in text
    assert GRID_PROOF_WATERMARK not in text
    # Chapter bookmark dest sits with the first body, after the opening \s1.
    rooms = text.index('#section("In My Father')
    way = text.index('#section("The Way, the Truth, and the Life")')
    ch14 = text.index("#outline-chapter(14)")
    drop14 = text.find("#chapter-drop(", text.find("#mark-run(\"JOHN · 14\")"))
    assert rooms < ch14 < drop14 < way
    rooms_keep = text.rfind("#keep-with[", 0, rooms)
    assert rooms_keep != -1
    rooms_end = text.find("]", drop14)
    assert rooms_keep < rooms < ch14 < drop14 < rooms_end < way
    way_keep = text.rfind("#keep-with[", 0, way)
    assert way_keep != -1
    assert way_keep < way


@pytest.mark.skipif(not USFM_ZIP.exists(), reason="official BSB USFM zip not present")
def test_real_usfm_matthew_drops_next_marker_and_osis_tails(tmp_path):
    out = tmp_path / "matthew.typ"
    books = generate_travel_typst(USFM_ZIP, out, books=("Matthew",), grid_proof=True)
    assert [book["book"] for book in books] == ["Matthew"]
    text = out.read_text(encoding="utf-8")
    assert "Next:" not in text
    assert "|1CH" not in text
    assert "|RUT" not in text
    assert "|ISA" not in text
    assert "1 Chronicles 2:9" in text
    assert "Abraham was the father of Isaac" in text


@pytest.mark.skipif(not USFM_ZIP.exists(), reason="official BSB USFM zip not present")
def test_real_usfm_psalm_119_lamp_title_keep_with_break(tmp_path):
    out = tmp_path / "psalms.typ"
    generate_travel_typst(USFM_ZIP, out, books=("Psalms",), grid_proof=True)
    text = out.read_text(encoding="utf-8")
    lamp = text.index('#section("Your Word Is a Lamp to My Feet")')
    aleph = text.index('#stanza("ALEPH")')
    mark = text.find('#mark-run("PSALM · 119")')
    drop = text.index("#chapter-drop(", mark)
    keep = text.rfind("#keep-with-break[", 0, lamp)
    assert keep != -1
    assert keep < lamp < aleph < drop
    assert text.find("]", drop) > aleph


def test_grid_proof_preamble_is_labeled_stand_in_not_loved_face():
    preamble = travel_preamble(grid_proof=True)
    assert GRID_PROOF_WATERMARK not in preamble
    assert "NOT FINAL FACE" not in preamble
    assert GRID_PROOF_FAMILY in preamble
    assert "grid-proof = true" in preamble
    assert "Never present this stand-in as the loved face" in preamble
    assert "proof-background" not in preamble
    assert "proof-mark" not in preamble
    assert "align(center, str(here().page() + folio-offset))" in preamble
    assert "#let folio-offset = 0" in preamble
    assert "columns: (1fr, auto, 1fr)" not in preamble
    assert MILO_TEXT_FAMILY in preamble
    default = travel_preamble()
    assert GRID_PROOF_WATERMARK not in default
    assert "grid-proof = false" in default
    assert 'body-font = "Source Serif 4"' not in default


def test_preamble_footnotes_run_in_not_stacked():
    preamble = travel_preamble()
    assert "Run-in notes" in preamble
    assert "query(footnote)" in preamble
    assert "footnote.entry(" in preamble
    assert "indent: 0pt" in preamble
    assert ".join([#h(0.7em)])" in preamble
    assert "notes.first().location()" in preamble
    grid = travel_preamble(grid_proof=True)
    assert "query(footnote)" in grid
    assert GRID_PROOF_WATERMARK not in grid


def test_preamble_footnotes_use_grey_ink():
    preamble = travel_preamble()
    fr, fg, fb = SPEC.footnote_ink_rgb
    assert fr == fg == fb
    assert fr > SPEC.ink_rgb[0]
    assert f"footnote-ink = rgb({fr}, {fg}, {fb})" in preamble
    assert "fill: footnote-ink" in preamble
    assert "show link: set text(fill: footnote-ink)" in preamble
    assert "stroke: 0.35pt + footnote-ink" in preamble
    grid = travel_preamble(grid_proof=True)
    assert "fill: footnote-ink" in grid


def test_preamble_section_heads_have_air_above_and_below():
    preamble = travel_preamble()
    section_at = preamble.index("#let section(title)")
    snippet = preamble[section_at : section_at + 220]
    assert "above: 1.5 * baseline-skip" in snippet
    assert "below: 0.5 * baseline-skip" in snippet
    assert "above: 2 * baseline-skip" not in snippet
    assert "sticky: true" in snippet
    assert "#let keep-with(body)" in preamble
    keep_at = preamble.index("#let keep-with(body)")
    keep_snippet = preamble[keep_at : keep_at + 180]
    assert "breakable: false" in keep_snippet
    assert "above: 1.5 * baseline-skip" in keep_snippet
    assert "above: 0pt" not in keep_snippet
    break_at = preamble.index("#let keep-with-break(body)")
    assert "above: 2.5 * baseline-skip" in preamble[break_at : break_at + 180]
    stanza_at = preamble.index("#let stanza(title)")
    assert "above: 0.5 * baseline-skip" in preamble[stanza_at : stanza_at + 160]
    xrefs_at = preamble.index("#let chapter-xrefs(")
    xref_snippet = preamble[xrefs_at : xrefs_at + 220]
    assert "below: 0.5 * baseline-skip" in xref_snippet
    assert "sticky: true" in xref_snippet
    grid = travel_preamble(grid_proof=True)
    assert "sticky: true" in grid[grid.index("#let section(title)") :]
    assert "#let keep-with(body)" in grid
    assert "#let keep-with-break(body)" in grid
    assert "#let stanza(title)" in grid
    book_at = preamble.index("#let book-title(name)")
    book_snippet = preamble[book_at : book_at + 280]
    assert "Berean Standard Bible" not in book_snippet
    assert "Travel print sample" not in book_snippet
    assert "sample:" not in book_snippet
    assert "2 * baseline-skip" in book_snippet
    assert "0.5 * baseline-skip" not in book_snippet
    assert "body-leading-gap" in preamble
    assert "leading: body-leading-gap" in preamble
    assert "hide-opening-chrome = true" in preamble
    shown = travel_preamble(hide_opening_chrome=False)
    assert "hide-opening-chrome = false" in shown


def test_book_part_slug_and_page_start(tmp_path):
    assert book_part_slug(1, "1 Samuel") == "01-1-samuel"
    assert book_part_slug(22, "Song of Songs") == "22-song-of-songs"
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "matt.typ"
    generate_travel_typst(
        usfm,
        out,
        books=("John",),
        hide_opening_chrome=False,
        page_start=81,
    )
    text = out.read_text()
    assert "hide-opening-chrome = false" in text
    assert "#let folio-offset = 80" in text
    assert "#counter(page).update(" not in text
    assert "str(here().page() + folio-offset)" in text


def test_preamble_pdf_outline_is_heading_bookmarks():
    preamble = travel_preamble()
    assert "#set heading(numbering: none)" in preamble
    assert "#show heading: none" in preamble
    assert "#let outline-book(name)" in preamble
    assert "#let outline-chapter(n)" in preamble
    assert "bookmarked: true" in preamble
    assert "outlined: false" in preamble
    assert "#outline(" not in preamble
    grid = travel_preamble(grid_proof=True)
    assert "#let outline-book(name)" in grid
    assert "#outline(" not in grid


def test_require_grid_proof_fonts_rejects_milo_as_stand_in(tmp_path):
    font_dir = tmp_path / "grid-proof"
    font_dir.mkdir()
    (font_dir / "MiloSerif-Text.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-TextItalic.otf").write_bytes(b"OTTO")
    found = classify_grid_proof_fonts(font_dir)
    assert found["regular"] == []
    assert found["italic"] == []
    with pytest.raises(GridProofFontError) as exc:
        require_grid_proof_fonts(font_dir)
    assert GRID_PROOF_FONT_MISSING_MESSAGE in str(exc.value)


def test_require_grid_proof_fonts_accepts_source_serif(tmp_path):
    font_dir = tmp_path / "grid-proof"
    font_dir.mkdir()
    (font_dir / "SourceSerif4-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-It.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-Bold.otf").write_bytes(b"OTTO")
    found = require_grid_proof_fonts(font_dir)
    assert len(found["regular"]) == 1
    assert len(found["italic"]) == 1
    assert found["bold"]


def test_grid_proof_writes_stand_in_typst_without_milo(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--grid-proof",
        "--no-compile",
    ])
    assert code == 0
    text = typ.read_text()
    assert GRID_PROOF_WATERMARK not in text
    assert "NOT FINAL FACE" not in text
    assert GRID_PROOF_FAMILY in text
    assert "The Gospel According to John" in text
    assert "#woc[" in text
    assert "#chapter-drop(" in text
    assert "grid-proof = true" in text
    assert "query(footnote)" in text
    assert "proof-background" not in text


def test_grid_proof_exits_2_without_stand_in_fonts(tmp_path, capsys):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--grid-proof",
    ])
    assert code == 2
    err = capsys.readouterr().err
    assert GRID_PROOF_FONT_MISSING_MESSAGE in err
    assert typ.exists()


def test_protestant_canon_is_sixty_six_books_in_order():
    assert len(PROTESTANT_CANON) == 66
    assert len(set(PROTESTANT_CANON)) == 66
    assert PROTESTANT_CANON[0] == "Genesis"
    assert PROTESTANT_CANON[38] == "Malachi"
    assert PROTESTANT_CANON[39] == "Matthew"
    assert PROTESTANT_CANON[42] == "John"
    assert PROTESTANT_CANON[43] == "Acts"
    assert PROTESTANT_CANON[-1] == "Revelation"


def test_select_travel_books_defaults_to_john():
    assert select_travel_books() == ["John"]
    assert select_travel_books(book_args=["Psalms", "Isaiah"]) == ["Psalms", "Isaiah"]


def test_select_travel_books_all_is_canon_order():
    names = select_travel_books(all_books=True)
    assert names == list(PROTESTANT_CANON)
    assert names.index("Malachi") + 1 == names.index("Matthew")
    assert select_travel_books(all_books=True, testament="ot")[-1] == "Malachi"
    assert select_travel_books(all_books=True, testament="nt")[0] == "Matthew"
    assert select_travel_books(all_books=True, testament="nt")[-1] == "Revelation"


def test_select_travel_books_rejects_book_and_all():
    with pytest.raises(ValueError, match="--all-books or --book"):
        select_travel_books(all_books=True, book_args=["John"])


def test_default_paths_keep_john_unless_all_books():
    pdf, typ, fonts = default_output_paths(grid_proof=True, all_books=False)
    assert pdf.name == "bsb-travel-john-grid-proof.pdf"
    assert typ.name == "john-grid-proof.typ"
    pdf, typ, fonts = default_output_paths(grid_proof=True, all_books=True)
    assert pdf.name == "bsb-travel-bible-grid-proof.pdf"
    assert typ.name == "bible-grid-proof.typ"
    assert "grid-proof" in str(fonts)
    pdf, typ, _ = default_output_paths(grid_proof=True, all_books=True, testament="ot")
    assert pdf.name == "bsb-travel-bible-ot-grid-proof.pdf"


def test_all_books_typst_is_canon_order_and_sample_only_on_first(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "bible.typ"
    books = generate_travel_typst(usfm, out, books=PROTESTANT_CANON)
    assert [book["book"] for book in books] == ["Genesis", "Psalms", "John"]
    text = out.read_text()
    assert text.index("#book-title(") < text.index("In the beginning.")
    assert text.index("In the beginning.") < text.index("Blessed is the man")
    assert text.index("Blessed is the man") < text.index("The Gospel According to John")
    assert text.count("#pagebreak()") == 2
    assert "Travel print sample" not in text
    assert "Berean Standard Bible" not in text
    assert '#book-title("Genesis")' in text
    assert "#mark-run(" in text
    assert text.index("#mark-run(") < text.index('#book-title("Genesis"')
    assert '#book-title("Psalm")' in text
    assert '#book-title("The Gospel According to John")' in text
    assert "#superscription[Psalms 1–41]" in text
    assert "A Psalm of David" in text
    assert "#inscription[Selah]" in text
    assert "#poetry(" in text
    assert "ALEPH" in text
    assert "BOOK I" in text
    assert "#counter(footnote).update(0)" in text
    assert "א" not in text
    assert '#outline-book("Genesis")' in text
    assert '#outline-book("Psalm")' in text
    assert '#outline-book("John")' in text
    assert text.index('#outline-book("Genesis")') < text.index('#book-title("Genesis"')
    assert text.index("#outline-chapter(1)") < text.index("In the beginning.")


def test_hebrew_script_detection():
    assert is_hebrew_script("א")
    assert is_hebrew_script(" ב ")
    assert not is_hebrew_script("ALEPH")
    assert not is_hebrew_script("Psalm")


def test_cli_all_books_no_compile_does_not_need_fonts(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--all-books",
        "--grid-proof",
        "--no-compile",
    ])
    assert code == 0
    assert not pdf.exists()
    text = typ.read_text()
    assert GRID_PROOF_WATERMARK not in text
    assert GRID_PROOF_FAMILY in text
    assert '#book-title("Genesis")' in text
    assert "Travel print sample" not in text
    assert "Berean Standard Bible" not in text
    assert "Stand-in face:" not in text


def test_cli_all_books_and_book_exits_2(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    with pytest.raises(SystemExit) as exc:
        main([
            str(usfm),
            str(tmp_path / "out.pdf"),
            "--all-books",
            "--book",
            "John",
            "--no-compile",
        ])
    assert exc.value.code == 2


def test_merge_travel_pdfs_offsets_outline(tmp_path):
    import fitz

    first = tmp_path / "ot.pdf"
    second = tmp_path / "nt.pdf"
    merged = tmp_path / "bible.pdf"
    ot = fitz.open()
    ot.new_page(width=342, height=504)
    ot.new_page(width=342, height=504)
    ot.set_toc([[1, "Genesis", 1], [2, "1", 1], [2, "2", 2]])
    ot.save(first)
    ot.close()
    nt = fitz.open()
    nt.new_page(width=342, height=504)
    nt.set_toc([[1, "Matthew", 1], [2, "1", 1]])
    nt.save(second)
    nt.close()
    merge_travel_pdfs([first, second], merged)
    with fitz.open(merged) as doc:
        assert doc.page_count == 3
        assert doc.get_toc() == [
            [1, "Genesis", 1],
            [2, "1", 1],
            [2, "2", 2],
            [1, "Matthew", 3],
            [2, "1", 3],
        ]


def test_random_qa_selection_is_seeded_and_mixed():
    from bsb_pdf_toolkit.compose_travel_random_qa import (
        RANDOM_QA_SEED,
        book_ranges_from_toc,
        page_chrome_failures,
        select_random_qa_leaves,
    )

    toc = [
        [1, "Genesis", 1],
        [2, "1", 1],
        [1, "Psalm", 20],
        [2, "1", 20],
        [2, "119", 30],
        [1, "Isaiah", 40],
        [1, "Obadiah", 50],
        [1, "Matthew", 52],
        [1, "John", 70],
        [1, "2 John", 80],
        [1, "Revelation", 81],
        [2, "22", 88],
    ]
    ranges = book_ranges_from_toc(toc, 90)
    assert ranges[0].name == "Genesis"
    assert ranges[0].start == 1 and ranges[0].end == 19
    assert ranges[-1].name == "Revelation" and ranges[-1].end == 90
    first = select_random_qa_leaves(ranges, toc, seed=RANDOM_QA_SEED, page_count=90)
    again = select_random_qa_leaves(ranges, toc, seed=RANDOM_QA_SEED, page_count=90)
    assert [leaf.page for leaf in first] == [leaf.page for leaf in again]
    pages = {leaf.page for leaf in first}
    assert 1 in pages
    assert 30 in pages
    assert 90 in pages
    roles = {leaf.role for leaf in first}
    assert {"opener", "poetry", "prose", "tiny", "ending", "uniform"} <= roles
    assert any(leaf.book == "Genesis" for leaf in first)
    assert any(leaf.book in {"Obadiah", "2 John"} for leaf in first if leaf.role == "tiny")
    assert any(leaf.book == "Matthew" or leaf.book == "John" for leaf in first if leaf.role == "opener")
    assert 14 <= len(first) <= 16
    assert page_chrome_failures("plain verse") == []
    assert "Berean Standard Bible" in page_chrome_failures("The Berean Standard Bible opens")


def test_selah_and_divine_name_spans():
    text = render_text_chunk(r"Wait on \nd the LORD\nd* . \qs Selah\qs*")
    assert "#divine[the LORD]" in text
    assert "#emph[Selah]" in text
    preamble = travel_preamble()
    assert "hyphenate: false" in preamble
    assert "#let divine(body) = text(hyphenate: false)[#smallcaps[#body]]" in preamble


def test_parse_facing_pairs_defaults_and_rejects_non_opening():
    from bsb_pdf_toolkit.compose_travel_spreads import DEFAULT_PAIRS, parse_pairs

    assert parse_pairs("2-3,4-5,10-11") == DEFAULT_PAIRS
    with pytest.raises(ValueError, match="facing"):
        parse_pairs("3-4")
    with pytest.raises(ValueError, match="facing"):
        parse_pairs("2-4")


def test_compose_spread_is_two_up_verso_left(tmp_path):
    import fitz

    from bsb_pdf_toolkit.compose_travel_spreads import (
        compose_spread_pdf,
        line_match_report,
        render_spread_pngs,
    )

    source = tmp_path / "john.pdf"
    src = fitz.open()
    for index in range(4):
        page = src.new_page(width=342, height=504)
        page.insert_text((40, 100), f"page-{index + 1}", fontsize=8.5)
    src.save(source)
    src.close()

    output = tmp_path / "spreads.pdf"
    pairs = compose_spread_pdf(source, output, ((2, 3),))
    assert pairs == [(2, 3)]
    with fitz.open(output) as doc:
        assert len(doc) == 1
        page = doc[0]
        assert page.rect.width == pytest.approx(684)
        assert page.rect.height == pytest.approx(504)
        text = page.get_text()
        assert "page-2" in text
        assert "page-3" in text
        hits = page.search_for("page-2")
        assert hits and hits[0].x1 < 342

    pngs = render_spread_pngs(output, tmp_path / "png", ((2, 3),), dpi=72)
    assert pngs == [tmp_path / "png" / "john-spread-02-03.png"]
    assert pngs[0].is_file()

    aligned = line_match_report(
        [100.0 + 10.5 * i for i in range(12)],
        [100.0 + 10.5 * i for i in range(12) if i != 1],
    )
    assert aligned["pass"]
    assert aligned["shared_ys"] >= 8
    assert aligned["phase_delta_pt"] == 0
    drifted = line_match_report(
        [100.0 + 10.5 * i for i in range(12)],
        [105.0 + 10.5 * i for i in range(12)],
    )
    assert not drifted["pass"]


def test_hotspot_books_and_required_leaves():
    from bsb_pdf_toolkit.compose_travel_hotspots import DEFAULT_HOTSPOTS, HOTSPOT_BOOKS

    assert HOTSPOT_BOOKS == ("Genesis", "Psalms", "Obadiah", "1 John", "Revelation")
    slugs = [spec.slug for spec in DEFAULT_HOTSPOTS]
    assert slugs == [
        "genesis-1",
        "psalm-1",
        "psalm-119",
        "obadiah",
        "1-john-3",
        "revelation-22",
    ]
    assert all(spec.book in HOTSPOT_BOOKS for spec in DEFAULT_HOTSPOTS)
    aleph = next(spec for spec in DEFAULT_HOTSPOTS if spec.slug == "psalm-119")
    assert "ALEPH" in aleph.needles
    assert "א" in aleph.forbid


def test_remap_outline_keeps_book_when_chapter_extracted():
    from bsb_pdf_toolkit.compose_travel_hotspots import remap_outline

    toc = [
        [1, "Matthew", 1],
        [2, "3", 5],
        [2, "4", 6],
        [2, "5", 7],
        [1, "John", 66],
        [2, "3", 70],
        [2, "14", 97],
    ]
    assert remap_outline(toc, [5, 6, 70, 97]) == [
        [1, "Matthew", 1],
        [2, "3", 1],
        [2, "4", 2],
        [1, "John", 3],
        [2, "3", 3],
        [2, "14", 4],
    ]
    # A leaf inside a chapter still maps that chapter, not only the dest page.
    assert remap_outline(toc, [81]) == [[1, "John", 1], [2, "3", 1]]
    assert remap_outline(toc, [1]) == [[1, "Matthew", 1]]
    assert remap_outline(toc, [4]) == []
    assert remap_outline(toc, [99]) == [[1, "John", 1], [2, "14", 1]]


def test_hotspot_page_selection_and_extract(tmp_path):
    import fitz

    from bsb_pdf_toolkit.compose_travel_hotspots import (
        BookFace,
        DEFAULT_OUTPUT,
        extract_sampler_pdf,
        render_hotspot_pngs,
        select_hotspot_pages,
    )

    catalog = [
        BookFace("Genesis", "Genesis", "Genesis"),
        BookFace("Psalms", "Psalm", "Psalm"),
        BookFace("Obadiah", "Obadiah", "Obadiah"),
        BookFace("1 John", "The First Letter of John", "1 John"),
        BookFace("Revelation", "The Revelation to John", "Revelation"),
    ]
    pages = [
        "Genesis\nIn the beginning God created the heavens and the earth.",
        "GENESIS · 2\nMore Genesis.",
        "PSALM · 1\nBlessed is the man who does not walk.",
        "PSALM · 118\nGive thanks.",
        "PSALM · 119\nALEPH\nBlessed are those whose way is blameless.",
        "Obadiah\nOBADIAH · 1\nThis is the vision of Obadiah:",
        "1 JOHN · 2\nThe First Letter of John\nLittle children.",
        "1 JOHN · 3\nBehold what manner of love the Father has given to us, that we should be called children of God.",
        "REVELATION · 21\nThe Revelation to John\nA new heaven.",
        "REVELATION · 22\nThe grace of the Lord Jesus be with all the saints. Amen.",
    ]
    chosen = select_hotspot_pages(pages, catalog)
    assert [spec.slug for spec, _ in chosen] == [
        "genesis-1",
        "psalm-1",
        "psalm-119",
        "obadiah",
        "1-john-3",
        "revelation-22",
    ]
    assert [page_no for _, page_no in chosen] == [1, 3, 5, 6, 8, 10]

    source = tmp_path / "hotspot-src.pdf"
    src = fitz.open()
    for index, text in enumerate(pages):
        page = src.new_page(width=342, height=504)
        page.insert_text((40, 80), text, fontsize=8.5)
    src.save(source)
    src.close()

    output = tmp_path / "sampler.pdf"
    extract_sampler_pdf(source, output, [page_no for _, page_no in chosen])
    with fitz.open(output) as doc:
        assert len(doc) == 6
        assert doc[0].rect.width == pytest.approx(342)
        assert "In the beginning" in doc[0].get_text()
        assert "ALEPH" in doc[2].get_text()
        assert "א" not in doc[2].get_text()
        assert "Amen" in doc[-1].get_text()

    pngs = render_hotspot_pngs(
        output,
        tmp_path / "hotspots",
        [spec.slug for spec, _ in chosen],
        dpi=72,
    )
    assert [path.name for path in pngs] == [
        "genesis-1.png",
        "psalm-1.png",
        "psalm-119.png",
        "obadiah.png",
        "1-john-3.png",
        "revelation-22.png",
    ]
    assert all(path.is_file() for path in pngs)
    assert DEFAULT_OUTPUT.name == "bsb-travel-hotspot-sampler-grid-proof.pdf"


def test_hotspot_rejects_hebrew_tofu_on_psalm_119():
    from bsb_pdf_toolkit.compose_travel_hotspots import BookFace, select_hotspot_pages

    catalog = [
        BookFace("Genesis", "Genesis", "Genesis"),
        BookFace("Psalms", "Psalm", "Psalm"),
        BookFace("Obadiah", "Obadiah", "Obadiah"),
        BookFace("1 John", "The First Letter of John", "1 John"),
        BookFace("Revelation", "The Revelation to John", "Revelation"),
    ]
    pages = [
        "Genesis\nIn the beginning God created.",
        "PSALM · 1\nBlessed is the man",
        "PSALM · 119\nALEPH א\nBlessed are those whose way is blameless.",
        "OBADIAH · 1\nObadiah",
        "1 JOHN · 3\nBehold what manner of love the Father has given to us, children of God",
        "REVELATION · 22\nAmen",
    ]
    with pytest.raises(ValueError, match="forbidden"):
        select_hotspot_pages(pages, catalog)


def test_hyphenation_qa_picks_densest_john_page():
    from bsb_pdf_toolkit.compose_travel_hyphenation import (
        DEFAULT_OUTPUT,
        HYPHEN_QA_BOOKS,
        BookFace,
        count_hyphen_breaks,
        pick_most_hyphens,
        select_hyphenation_pages,
    )

    assert HYPHEN_QA_BOOKS == ("Genesis", "Psalms", "John")
    assert DEFAULT_OUTPUT.name == "bsb-travel-hyphenation-qa-grid-proof.pdf"
    assert count_hyphen_breaks("perform\u00ad\ning") == 1
    assert pick_most_hyphens(["aa", "prepa\u00ad", "bb\u00ad cc\u00ad"], 1, 3) == 3

    catalog = [
        BookFace("Genesis", "Genesis", "Genesis"),
        BookFace("Psalms", "Psalm", "Psalm"),
        BookFace("John", "The Gospel According to John", "John"),
    ]
    pages = [
        "GENESIS · 1\nIn the beginning God created.",
        "PSALM · 1\nBlessed is the man.",
        "PSALM · 119\nALEPH\nBlessed are those whose way is blameless.",
        "JOHN · 3\nFor God so loved the world.",
        "JOHN · 4\nsurprised that He was speak\u00ad\ning.",
    ]
    chosen = select_hyphenation_pages(pages, catalog)
    assert [spec.slug for spec, _ in chosen] == ["john-prose", "psalm-119", "genesis-1"]
    assert [page_no for _, page_no in chosen] == [5, 3, 1]
    assert chosen[0][0].require == ()


def test_poetry_lines_are_ragged_not_justified():
    preamble = travel_preamble()
    poetry_at = preamble.index("#let poetry(")
    snippet = preamble[poetry_at : poetry_at + 420]
    assert "justify: false" in snippet
    assert "hanging-indent: 0.18in" in snippet
    assert "0.18in * calc.max(0, level - 1)" in snippet
    assert "leading: leading-gap" in snippet
    global_par = preamble[preamble.index("#set par(") : preamble.index("#let poetry(")]
    assert "justify: true" in global_par
    assert "leading: body-leading-gap" in global_par


def test_poetry_qa_paths_and_leaf_order():
    from bsb_pdf_toolkit.compose_travel_poetry import (
        DEFAULT_OUTPUT,
        POETRY_QA_BOOKS,
        POETRY_QA_LEAVES,
    )

    assert POETRY_QA_BOOKS == ("Genesis", "Psalms")
    assert DEFAULT_OUTPUT.name == "bsb-travel-poetry-qa-grid-proof.pdf"
    assert [spec.slug for spec in POETRY_QA_LEAVES] == ["psalm-1", "psalm-119"]


def test_travel_typst_emits_verse_chapter_for_running_headers(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "john.typ"
    generate_travel_typst(usfm, out, books=("John",))
    text = out.read_text()
    assert '#verse("https://route.bible/John.1.2", 1, 2)[' in text
    assert "#chapter-drop(" in text
    assert "#let format-run-head(" in text
    assert "query(<run-verse>)" in text


def test_header_qa_paths_and_range_detection():
    from bsb_pdf_toolkit.compose_travel_headers import (
        DEFAULT_OUTPUT,
        HEADER_PAGES,
        HEADER_QA_BOOKS,
        HEADER_SLUGS,
        page_has_verse_header,
    )

    assert HEADER_QA_BOOKS == ("John",)
    assert HEADER_PAGES == (2, 3, 6, 10)
    assert HEADER_SLUGS == ("john-p02", "john-p03", "john-p06", "john-p10")
    assert DEFAULT_OUTPUT.name == "bsb-travel-running-headers-qa-grid-proof.pdf"
    assert page_has_verse_header("JOHN · 4:17–38\nThe woman said")
    assert page_has_verse_header("JOHN · 3:31–4:2\nHe must increase")
    assert not page_has_verse_header("JOHN · 4\nThe woman said")
    assert not page_has_verse_header("The Gospel According to John")


def test_woc_qa_paths_and_required_leaves():
    from bsb_pdf_toolkit.compose_travel_woc import (
        DEFAULT_OUTPUT,
        WOC_QA_BOOKS,
        WOC_QA_LEAVES,
        WOC_REQUIRED_SLUGS,
    )

    assert WOC_QA_BOOKS == ("Matthew", "John")
    assert DEFAULT_OUTPUT.name == "bsb-travel-woc-qa-grid-proof.pdf"
    slugs = [spec.slug for spec in WOC_QA_LEAVES]
    assert slugs[:3] == ["matthew-baptism", "matthew-temptation", "john-farewell"]
    assert WOC_REQUIRED_SLUGS == {"matthew-baptism", "john-farewell"}
    assert all(spec.book in WOC_QA_BOOKS for spec in WOC_QA_LEAVES)


def test_woc_page_selection_skips_duplicate_matthew_leaf():
    from bsb_pdf_toolkit.compose_travel_hotspots import BookFace
    from bsb_pdf_toolkit.compose_travel_woc import select_woc_pages

    catalog = [
        BookFace("Matthew", "Matthew", "Matthew"),
        BookFace("John", "The Gospel According to John", "John"),
    ]
    pages = [
        "MATTHEW · 3\nLet it be so now. Man shall not live on bread alone.",
        "MATTHEW · 5\nBlessed are the poor in spirit, for theirs is the kingdom of heaven.",
        "JOHN · 3\nFor God so loved the world that He gave His one and only Son.",
        "JOHN · 14\nDo not let your hearts be troubled. You believe in God.",
    ]
    chosen = select_woc_pages(pages, catalog)
    assert [spec.slug for spec, _ in chosen] == [
        "matthew-baptism",
        "matthew-sermon",
        "john-loved",
        "john-farewell",
    ]
    assert [page_no for _, page_no in chosen] == [1, 2, 3, 4]


def test_woc_page_selection_keeps_four_when_distinct():
    from bsb_pdf_toolkit.compose_travel_hotspots import BookFace
    from bsb_pdf_toolkit.compose_travel_woc import select_woc_pages

    catalog = [
        BookFace("Matthew", "Matthew", "Matthew"),
        BookFace("John", "The Gospel According to John", "John"),
    ]
    pages = [
        "MATTHEW · 3\nLet it be so now, Jesus replied.",
        "MATTHEW · 4\nMan shall not live on bread alone, but on every word.",
        "JOHN · 3\nFor God so loved the world that He gave His one and only Son.",
        "JOHN · 14\nDo not let your hearts be troubled. You believe in God.",
    ]
    chosen = select_woc_pages(pages, catalog)
    assert [spec.slug for spec, _ in chosen] == [
        "matthew-baptism",
        "matthew-temptation",
        "john-loved",
        "john-farewell",
    ]
    assert [page_no for _, page_no in chosen] == [1, 2, 3, 4]


def test_woc_speech_and_typst_helpers():
    from bsb_pdf_toolkit.compose_travel_woc import (
        page_has_woc_speech,
        speech_wrapped_in_woc,
        typst_exercises_woc,
        validate_woc_pages,
        validate_woc_typst,
    )
    from bsb_pdf_toolkit.compose_travel_hotspots import HotspotSpec

    assert page_has_woc_speech("Let it be so now, Jesus replied.")
    assert page_has_woc_speech("Do not let your hearts be trou- bled.")
    assert not page_has_woc_speech("In the beginning was the Word.")

    typst = (
        "#let woc-blue = rgb(28, 56, 110)\n"
        "#let woc(body) = text(fill: woc-blue)[#body]\n"
        "#woc[Let it be so now]\n"
        "#woc[Do not let your hearts be troubled]\n"
    )
    assert typst_exercises_woc(typst)
    assert speech_wrapped_in_woc(typst, "Let it be so now")
    validate_woc_typst(typst, ("Let it be so now", "Do not let your hearts be troubled"))

    baptism = HotspotSpec(
        slug="matthew-baptism",
        label="Matthew 3 baptism",
        book="Matthew",
        pick="contains",
        needles=("Let it be so now",),
        require=("Let it be so now",),
    )
    farewell = HotspotSpec(
        slug="john-farewell",
        label="John 14 farewell",
        book="John",
        pick="contains",
        needles=("Do not let your hearts be troubled",),
        require=("Do not let your hearts be troubled",),
    )
    loved = HotspotSpec(
        slug="john-loved",
        label="John 3 loved the world",
        book="John",
        pick="contains",
        needles=("For God so loved the world",),
        require=("For God so loved the world",),
    )
    with pytest.raises(ValueError, match="missing required text"):
        validate_woc_pages(
            [(baptism, 1), (farewell, 2), (loved, 3)],
            [
                "In the beginning was the Word.",
                "Do not let your hearts be troubled.",
                "For God so loved the world.",
            ],
        )
    with pytest.raises(ValueError, match="does not exercise"):
        validate_woc_typst("no cobalt here", ("Let it be so now",))
