"""Unit tests for the compact travel John composer."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(REPO_ROOT / "src"))

from bsb_pdf_toolkit.generate_travel_pdf import (  # noqa: E402
    FONT_MISSING_MESSAGE,
    GRID_PROOF_FAMILY,
    GRID_PROOF_FONT_MISSING_MESSAGE,
    GRID_PROOF_WATERMARK,
    MILO_TEXT_FAMILY,
    PROTESTANT_CANON,
    SAMPLE_SUBTITLE,
    SPEC,
    GridProofFontError,
    MiloFontError,
    classify_grid_proof_fonts,
    classify_milo_fonts,
    default_output_paths,
    footnote_markup,
    generate_travel_typst,
    is_hebrew_script,
    leading_gap_pt,
    main,
    measure_em,
    paragraph_markup,
    render_text_chunk,
    require_grid_proof_fonts,
    require_milo_fonts,
    select_travel_books,
    travel_preamble,
    verse_segments_travel,
    xref_markup,
)
from bsb_pdf_toolkit.generate_typst_pdf import parse_usfm_zip  # noqa: E402

USFM_ZIP = REPO_ROOT / "drafts" / "primary" / "source" / "engbsb_usfm.zip"

SAMPLE_USFM = r"""
\id JHN Autogenerated BSB by bsb2usfm
\usfm 3.1
\h John
\toc1 The Gospel According to John
\mt1 John
\c 1
\s1 The Beginning
\r (\ref Genesis 1:1–2|GEN 1:1-2\ref*; \ref Hebrews 11:1–3|HEB 11:1-3\ref*)
\p \v 1 In the beginning was the Word, and the Word was with God, and the Word was God. \v 2 He was with God in the beginning.
\s1 The First Disciples
\p \v 38 Jesus turned and saw them following. \wj “What do you want?”\wj* He asked.
\p \wj \v 39 “Come and see,”\wj* He replied.
\p \v 16 \wj For God so loved the world that He gave His one and only\f + \fr 3:16 \ft Or \ft only begotten \ft or \fqa unique\ft ; also in verse 18\f* Son.\wj*
\c 2
\s1 The Wedding at Cana
\p \v 1 On the third day a wedding took place at Cana in Galilee.
\pc JESUS OF NAZARETH, THE KING OF THE JEWS.
""".strip()


SAMPLE_PSA = r"""
\id PSA Autogenerated BSB by bsb2usfm
\h Psalm
\toc1 Psalm
\c 1
\ms BOOK I
\d Psalms 1–41
\q1 \v 1 Blessed is the man who does not walk.
\c 3
\d \v 1 A Psalm of David, when he fled from his son Absalom.
\q1 O LORD, how my foes have increased!
\qr Selah
\c 119
\qa ALEPH
\q1 \v 1 Blessed are those whose way is blameless.
""".strip()


def write_sample_zip(path: Path) -> Path:
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("bsb_usfm/JHN.usfm", SAMPLE_USFM)
        zf.writestr("bsb_usfm/GEN.usfm", "\\id GEN\n\\h Genesis\n\\c 1\n\\p \\v 1 In the beginning.\n")
        zf.writestr("bsb_usfm/PSA.usfm", SAMPLE_PSA)
    return path


def test_spec_line_matches_page():
    text_block_in = SPEC.lines_per_page * SPEC.baseline_pt / 72.0
    assert SPEC.trim_width_in == 4.75
    assert SPEC.trim_height_in == 7.0
    assert SPEC.body_pt == 8.5
    assert SPEC.baseline_pt == 10.5
    assert SPEC.margin_inside_in + SPEC.margin_outside_in + SPEC.measure_in == pytest.approx(4.75)
    assert SPEC.margin_head_in + SPEC.margin_foot_in + text_block_in == pytest.approx(7.0)
    assert SPEC.target_cpl_min == 60
    assert SPEC.target_cpl_max == 70
    em = measure_em()
    assert 30 <= em <= 34
    assert leading_gap_pt() == 2.0


def test_preamble_is_milo_text_not_a_substitute():
    preamble = travel_preamble()
    assert MILO_TEXT_FAMILY in preamble
    assert "MiloSerif-Text" in preamble
    assert "fallback: false" in preamble
    assert 'lang: "en"' in preamble
    assert "hyphenate: true" in preamble
    assert 'linebreaks: "optimized"' in preamble
    assert "overhang: true" in preamble
    assert "Source Serif" not in preamble or "Do not substitute Source Serif" in preamble
    assert "Lexend" not in preamble
    assert "WeasyPrint" not in preamble
    assert str(SPEC.woc_rgb[0]) in preamble


def test_require_milo_fonts_fails_closed_on_empty_dir(tmp_path):
    empty = tmp_path / "milo"
    empty.mkdir()
    with pytest.raises(MiloFontError) as exc:
        require_milo_fonts(empty)
    assert FONT_MISSING_MESSAGE in str(exc.value)


def test_require_milo_fonts_rejects_source_serif_substitute(tmp_path):
    font_dir = tmp_path / "milo"
    font_dir.mkdir()
    (font_dir / "SourceSerif4-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-It.otf").write_bytes(b"OTTO")
    found = classify_milo_fonts(font_dir)
    assert found["text"] == []
    with pytest.raises(MiloFontError) as exc:
        require_milo_fonts(font_dir)
    assert FONT_MISSING_MESSAGE in str(exc.value)


def test_require_milo_fonts_accepts_documented_names(tmp_path):
    font_dir = tmp_path / "milo"
    font_dir.mkdir()
    (font_dir / "MiloSerif-Text.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-TextItalic.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-Bold.otf").write_bytes(b"OTTO")
    found = require_milo_fonts(font_dir)
    assert len(found["text"]) == 1
    assert len(found["text-italic"]) == 1
    assert found["regular"]
    assert found["bold"]


def test_print_target_exits_2_without_fonts(tmp_path, capsys):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([str(usfm), str(pdf), "--typst-out", str(typ), "--font-dir", str(tmp_path / "missing")])
    assert code == 2
    err = capsys.readouterr().err
    assert FONT_MISSING_MESSAGE in err
    assert typ.exists()


def test_no_compile_writes_typst_without_fonts(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--no-compile",
    ])
    assert code == 0
    text = typ.read_text()
    assert "The Gospel According to John" in text
    assert "#woc[" in text
    assert "#footnote[" in text
    assert "#chapter-xrefs[" in text
    assert "#chapter-drop(" in text
    assert "Genesis 1:1" in text
    assert "#inscription[" in text
    assert "In the beginning was the Word" in text
    assert "Source Serif" not in text.split("Do not substitute Source Serif")[-1]


def test_parse_filters_to_john_only(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    books = parse_usfm_zip(usfm, book_names=["John"])
    assert [book["book"] for book in books] == ["John"]
    assert books[0]["title"] == "The Gospel According to John"


def test_words_of_christ_and_verse_inside_wj():
    segs = verse_segments_travel(
        r"\wj \v 39 “Come and see,”\wj* He replied.",
        "John",
        1,
    )
    assert segs[0][0] == 39
    assert "#woc[" in segs[0][2]
    assert "Come and see" in segs[0][2]
    assert "He replied" in segs[0][2]
    assert segs[0][2].index("#woc[") < segs[0][2].index("Come and see")


def test_words_of_christ_span_verses_same_paragraph():
    raw = (
        r'\v 5 Jesus answered, \wj “Truly, truly, I tell you. '
        r'\v 6 Flesh is born of flesh.”\wj*'
    )
    segs = verse_segments_travel(raw, "John", 3)
    assert segs[0][0] == 5
    assert segs[1][0] == 6
    assert "#woc[" in segs[0][2]
    assert "#woc[" in segs[1][2]
    assert "Flesh is born" in segs[1][2]


def test_footnote_inside_woc_keeps_note():
    raw = (
        r"\v 16 \wj For God so loved the world\f + \fr 3:16 \ft Or \fqa unique\f* Son.\wj*"
    )
    segs = verse_segments_travel(raw, "John", 3)
    body = segs[0][2]
    assert "#woc[" in body
    assert "#footnote[" in body
    assert "unique" in body


def test_xref_markup_strips_wrapping_parens():
    text = xref_markup(r"(\ref Genesis 1:1–2|GEN 1:1-2\ref*; \ref Hebrews 11:1–3|HEB 11:1-3\ref*)")
    assert text.startswith("#link(")
    assert "Genesis 1:1" in text
    assert not text.startswith("(")


def test_fqa_becomes_italic():
    markup = footnote_markup(r"+ \fr 1:5 \ft Or \fqa comprehended")
    assert "#emph[comprehended]" in markup


def test_psalm_descriptive_title_with_verse_keeps_drop():
    para = {
        "marker": "d",
        "raw": r"\v 1 A Psalm of David, when he fled from his son Absalom.",
    }
    lines = paragraph_markup(para, "Ps", 3, chapter_open=True)
    assert any("#chapter-drop(" in line for line in lines)
    assert any("A Psalm of David" in line for line in lines)


def test_chapter_open_drop_uses_only_first_verse():
    para = {
        "marker": "p",
        "raw": r"\v 1 In the beginning was the Word. \v 2 He was with God.",
    }
    lines = paragraph_markup(para, "John", 1, chapter_open=True)
    assert any("#chapter-drop(" in line for line in lines)
    assert any("#verse(" in line and "2" in line for line in lines)


def test_verse_number_is_boxed_in_preamble():
    preamble = travel_preamble()
    assert "#box[#vnum(n)#h(0.12em)]" in preamble
    assert "place(center + horizon)" in preamble


def test_preamble_defines_chapter_state_before_page_header():
    preamble = travel_preamble()
    assert preamble.index('#let chapter-label = state("chapter-label"') < preamble.index("#set page(")
    assert preamble.index("#let mark-run(label)") < preamble.index("#set page(")
    assert "query(<run-head>)" in preamble


def test_preamble_resets_footnote_letters_in_page_header():
    preamble = travel_preamble()
    header_at = preamble.index("header: context")
    footer_at = preamble.index("footer: context")
    reset_at = preamble.index("counter(footnote).update(0)", header_at)
    assert reset_at < footer_at
    assert '#set footnote(numbering: "a")' in preamble
    assert "starts at \"a\" again" in preamble
    grid = travel_preamble(grid_proof=True)
    assert grid.index("counter(footnote).update(0)", grid.index("header: context")) < grid.index(
        "footer: context"
    )


def test_generate_travel_typst_john_sample(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "john.typ"
    books = generate_travel_typst(usfm, out, books=("John",))
    text = out.read_text()
    assert books[0]["book"] == "John"
    assert text.count("#book-title") == 1
    assert "Genesis" not in text or "Genesis 1:1" in text
    assert "In the beginning." not in text
    assert "#set page(" in text
    assert "4.75in" in text or "4.75" in text


@pytest.mark.skipif(not USFM_ZIP.exists(), reason="official BSB USFM zip not present")
def test_real_usfm_john_preserves_corpus_text(tmp_path):
    out = tmp_path / "john.typ"
    books = generate_travel_typst(USFM_ZIP, out, books=("John",))
    assert [book["book"] for book in books] == ["John"]
    assert len(books[0]["chapters"]) == 21
    text = out.read_text(encoding="utf-8")
    assert "For God so loved the world" in text
    assert "In the beginning was the Word" in text
    assert "#woc[" in text
    assert text.count("#chapter-drop(") == 21
    assert "Source Serif 4" not in text
    assert "Lexend" not in text
    assert GRID_PROOF_WATERMARK not in text


def test_grid_proof_preamble_is_labeled_stand_in_not_loved_face():
    preamble = travel_preamble(grid_proof=True)
    assert GRID_PROOF_WATERMARK in preamble
    assert GRID_PROOF_FAMILY in preamble
    assert "grid-proof = true" in preamble
    assert "Never present this stand-in as the loved face" in preamble
    assert "proof-background" in preamble
    assert MILO_TEXT_FAMILY in preamble
    default = travel_preamble()
    assert GRID_PROOF_WATERMARK not in default
    assert "grid-proof = false" in default
    assert 'body-font = "Source Serif 4"' not in default


def test_require_grid_proof_fonts_rejects_milo_as_stand_in(tmp_path):
    font_dir = tmp_path / "grid-proof"
    font_dir.mkdir()
    (font_dir / "MiloSerif-Text.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-TextItalic.otf").write_bytes(b"OTTO")
    found = classify_grid_proof_fonts(font_dir)
    assert found["regular"] == []
    assert found["italic"] == []
    with pytest.raises(GridProofFontError) as exc:
        require_grid_proof_fonts(font_dir)
    assert GRID_PROOF_FONT_MISSING_MESSAGE in str(exc.value)


def test_require_grid_proof_fonts_accepts_source_serif(tmp_path):
    font_dir = tmp_path / "grid-proof"
    font_dir.mkdir()
    (font_dir / "SourceSerif4-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-It.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-Bold.otf").write_bytes(b"OTTO")
    found = require_grid_proof_fonts(font_dir)
    assert len(found["regular"]) == 1
    assert len(found["italic"]) == 1
    assert found["bold"]


def test_grid_proof_writes_watermarked_typst_without_milo(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--grid-proof",
        "--no-compile",
    ])
    assert code == 0
    text = typ.read_text()
    assert GRID_PROOF_WATERMARK in text
    assert GRID_PROOF_FAMILY in text
    assert "The Gospel According to John" in text
    assert "#woc[" in text
    assert "#chapter-drop(" in text
    assert "grid-proof = true" in text


def test_grid_proof_exits_2_without_stand_in_fonts(tmp_path, capsys):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--grid-proof",
    ])
    assert code == 2
    err = capsys.readouterr().err
    assert GRID_PROOF_FONT_MISSING_MESSAGE in err
    assert typ.exists()


def test_protestant_canon_is_sixty_six_books_in_order():
    assert len(PROTESTANT_CANON) == 66
    assert len(set(PROTESTANT_CANON)) == 66
    assert PROTESTANT_CANON[0] == "Genesis"
    assert PROTESTANT_CANON[38] == "Malachi"
    assert PROTESTANT_CANON[39] == "Matthew"
    assert PROTESTANT_CANON[42] == "John"
    assert PROTESTANT_CANON[43] == "Acts"
    assert PROTESTANT_CANON[-1] == "Revelation"


def test_select_travel_books_defaults_to_john():
    assert select_travel_books() == ["John"]
    assert select_travel_books(book_args=["Psalms", "Isaiah"]) == ["Psalms", "Isaiah"]


def test_select_travel_books_all_is_canon_order():
    names = select_travel_books(all_books=True)
    assert names == list(PROTESTANT_CANON)
    assert names.index("Malachi") + 1 == names.index("Matthew")
    assert select_travel_books(all_books=True, testament="ot")[-1] == "Malachi"
    assert select_travel_books(all_books=True, testament="nt")[0] == "Matthew"
    assert select_travel_books(all_books=True, testament="nt")[-1] == "Revelation"


def test_select_travel_books_rejects_book_and_all():
    with pytest.raises(ValueError, match="--all-books or --book"):
        select_travel_books(all_books=True, book_args=["John"])


def test_default_paths_keep_john_unless_all_books():
    pdf, typ, fonts = default_output_paths(grid_proof=True, all_books=False)
    assert pdf.name == "bsb-travel-john-grid-proof.pdf"
    assert typ.name == "john-grid-proof.typ"
    pdf, typ, fonts = default_output_paths(grid_proof=True, all_books=True)
    assert pdf.name == "bsb-travel-bible-grid-proof.pdf"
    assert typ.name == "bible-grid-proof.typ"
    assert "grid-proof" in str(fonts)
    pdf, typ, _ = default_output_paths(grid_proof=True, all_books=True, testament="ot")
    assert pdf.name == "bsb-travel-bible-ot-grid-proof.pdf"


def test_all_books_typst_is_canon_order_and_sample_only_on_first(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "bible.typ"
    books = generate_travel_typst(usfm, out, books=PROTESTANT_CANON)
    assert [book["book"] for book in books] == ["Genesis", "Psalms", "John"]
    text = out.read_text()
    assert text.index("#book-title(") < text.index("In the beginning.")
    assert text.index("In the beginning.") < text.index("Blessed is the man")
    assert text.index("Blessed is the man") < text.index("The Gospel According to John")
    assert text.count("#pagebreak()") == 2
    assert text.count(SAMPLE_SUBTITLE) == 1
    assert '#book-title("Genesis", sample: true)' in text
    assert "#mark-run(" in text
    assert text.index("#mark-run(") < text.index('#book-title("Genesis"')
    assert '#book-title("Psalm", sample: false)' in text
    assert '#book-title("The Gospel According to John", sample: false)' in text
    assert "#superscription[Psalms 1–41]" in text
    assert "A Psalm of David" in text
    assert "#inscription[Selah]" in text
    assert "ALEPH" in text
    assert "BOOK I" in text
    assert "#counter(footnote).update(0)" in text
    assert "א" not in text


def test_hebrew_script_detection():
    assert is_hebrew_script("א")
    assert is_hebrew_script(" ב ")
    assert not is_hebrew_script("ALEPH")
    assert not is_hebrew_script("Psalm")


def test_cli_all_books_no_compile_does_not_need_fonts(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--all-books",
        "--grid-proof",
        "--no-compile",
    ])
    assert code == 0
    assert not pdf.exists()
    text = typ.read_text()
    assert GRID_PROOF_WATERMARK in text
    assert '#book-title("Genesis", sample: true)' in text
    assert "Travel print sample" in text
    assert text.count("Travel print sample") == 1


def test_cli_all_books_and_book_exits_2(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    with pytest.raises(SystemExit) as exc:
        main([
            str(usfm),
            str(tmp_path / "out.pdf"),
            "--all-books",
            "--book",
            "John",
            "--no-compile",
        ])
    assert exc.value.code == 2


def test_selah_and_divine_name_spans():
    text = render_text_chunk(r"Wait on \nd the LORD\nd* . \qs Selah\qs*")
    assert "#smallcaps[the LORD]" in text
    assert "#emph[Selah]" in text


def test_parse_facing_pairs_defaults_and_rejects_non_opening():
    from bsb_pdf_toolkit.compose_travel_spreads import DEFAULT_PAIRS, parse_pairs

    assert parse_pairs("2-3,4-5,10-11") == DEFAULT_PAIRS
    with pytest.raises(ValueError, match="facing"):
        parse_pairs("3-4")
    with pytest.raises(ValueError, match="facing"):
        parse_pairs("2-4")


def test_compose_spread_is_two_up_verso_left(tmp_path):
    import fitz

    from bsb_pdf_toolkit.compose_travel_spreads import (
        compose_spread_pdf,
        line_match_report,
        render_spread_pngs,
    )

    source = tmp_path / "john.pdf"
    src = fitz.open()
    for index in range(4):
        page = src.new_page(width=342, height=504)
        page.insert_text((40, 100), f"page-{index + 1}", fontsize=8.5)
    src.save(source)
    src.close()

    output = tmp_path / "spreads.pdf"
    pairs = compose_spread_pdf(source, output, ((2, 3),))
    assert pairs == [(2, 3)]
    with fitz.open(output) as doc:
        assert len(doc) == 1
        page = doc[0]
        assert page.rect.width == pytest.approx(684)
        assert page.rect.height == pytest.approx(504)
        text = page.get_text()
        assert "page-2" in text
        assert "page-3" in text
        hits = page.search_for("page-2")
        assert hits and hits[0].x1 < 342

    pngs = render_spread_pngs(output, tmp_path / "png", ((2, 3),), dpi=72)
    assert pngs == [tmp_path / "png" / "john-spread-02-03.png"]
    assert pngs[0].is_file()

    aligned = line_match_report(
        [100.0 + 10.5 * i for i in range(12)],
        [100.0 + 10.5 * i for i in range(12) if i != 1],
    )
    assert aligned["pass"]
    assert aligned["shared_ys"] >= 8
    assert aligned["phase_delta_pt"] == 0
    drifted = line_match_report(
        [100.0 + 10.5 * i for i in range(12)],
        [105.0 + 10.5 * i for i in range(12)],
    )
    assert not drifted["pass"]
