"""Unit tests for the compact travel John composer."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(REPO_ROOT / "src"))

from bsb_pdf_toolkit.generate_travel_pdf import (  # noqa: E402
    FONT_MISSING_MESSAGE,
    MILO_TEXT_FAMILY,
    SPEC,
    MiloFontError,
    classify_milo_fonts,
    footnote_markup,
    generate_travel_typst,
    leading_gap_pt,
    main,
    measure_em,
    paragraph_markup,
    require_milo_fonts,
    travel_preamble,
    verse_segments_travel,
    xref_markup,
)
from bsb_pdf_toolkit.generate_typst_pdf import parse_usfm_zip  # noqa: E402

USFM_ZIP = REPO_ROOT / "drafts" / "primary" / "source" / "engbsb_usfm.zip"

SAMPLE_USFM = r"""
\id JHN Autogenerated BSB by bsb2usfm
\usfm 3.1
\h John
\toc1 The Gospel According to John
\mt1 John
\c 1
\s1 The Beginning
\r (\ref Genesis 1:1–2|GEN 1:1-2\ref*; \ref Hebrews 11:1–3|HEB 11:1-3\ref*)
\p \v 1 In the beginning was the Word, and the Word was with God, and the Word was God. \v 2 He was with God in the beginning.
\s1 The First Disciples
\p \v 38 Jesus turned and saw them following. \wj “What do you want?”\wj* He asked.
\p \wj \v 39 “Come and see,”\wj* He replied.
\p \v 16 \wj For God so loved the world that He gave His one and only\f + \fr 3:16 \ft Or \ft only begotten \ft or \fqa unique\ft ; also in verse 18\f* Son.\wj*
\c 2
\s1 The Wedding at Cana
\p \v 1 On the third day a wedding took place at Cana in Galilee.
\pc JESUS OF NAZARETH, THE KING OF THE JEWS.
""".strip()


def write_sample_zip(path: Path) -> Path:
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("bsb_usfm/JHN.usfm", SAMPLE_USFM)
        zf.writestr("bsb_usfm/GEN.usfm", "\\id GEN\n\\h Genesis\n\\c 1\n\\p \\v 1 In the beginning.\n")
    return path


def test_spec_line_matches_page():
    text_block_in = SPEC.lines_per_page * SPEC.baseline_pt / 72.0
    assert SPEC.trim_width_in == 4.75
    assert SPEC.trim_height_in == 7.0
    assert SPEC.body_pt == 8.5
    assert SPEC.baseline_pt == 10.5
    assert SPEC.margin_inside_in + SPEC.margin_outside_in + SPEC.measure_in == pytest.approx(4.75)
    assert SPEC.margin_head_in + SPEC.margin_foot_in + text_block_in == pytest.approx(7.0)
    assert SPEC.target_cpl_min == 60
    assert SPEC.target_cpl_max == 70
    em = measure_em()
    assert 30 <= em <= 34
    assert leading_gap_pt() == 2.0


def test_preamble_is_milo_text_not_a_substitute():
    preamble = travel_preamble()
    assert MILO_TEXT_FAMILY in preamble
    assert "MiloSerif-Text" in preamble
    assert "fallback: false" in preamble
    assert 'lang: "en"' in preamble
    assert "hyphenate: true" in preamble
    assert 'linebreaks: "optimized"' in preamble
    assert "overhang: true" in preamble
    assert "Source Serif" not in preamble or "Do not substitute Source Serif" in preamble
    assert "Lexend" not in preamble
    assert "WeasyPrint" not in preamble
    assert str(SPEC.woc_rgb[0]) in preamble


def test_require_milo_fonts_fails_closed_on_empty_dir(tmp_path):
    empty = tmp_path / "milo"
    empty.mkdir()
    with pytest.raises(MiloFontError) as exc:
        require_milo_fonts(empty)
    assert FONT_MISSING_MESSAGE in str(exc.value)


def test_require_milo_fonts_rejects_source_serif_substitute(tmp_path):
    font_dir = tmp_path / "milo"
    font_dir.mkdir()
    (font_dir / "SourceSerif4-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "SourceSerif4-It.otf").write_bytes(b"OTTO")
    found = classify_milo_fonts(font_dir)
    assert found["text"] == []
    with pytest.raises(MiloFontError) as exc:
        require_milo_fonts(font_dir)
    assert FONT_MISSING_MESSAGE in str(exc.value)


def test_require_milo_fonts_accepts_documented_names(tmp_path):
    font_dir = tmp_path / "milo"
    font_dir.mkdir()
    (font_dir / "MiloSerif-Text.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-TextItalic.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-Regular.otf").write_bytes(b"OTTO")
    (font_dir / "MiloSerif-Bold.otf").write_bytes(b"OTTO")
    found = require_milo_fonts(font_dir)
    assert len(found["text"]) == 1
    assert len(found["text-italic"]) == 1
    assert found["regular"]
    assert found["bold"]


def test_print_target_exits_2_without_fonts(tmp_path, capsys):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([str(usfm), str(pdf), "--typst-out", str(typ), "--font-dir", str(tmp_path / "missing")])
    assert code == 2
    err = capsys.readouterr().err
    assert FONT_MISSING_MESSAGE in err
    assert typ.exists()


def test_no_compile_writes_typst_without_fonts(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    pdf = tmp_path / "out.pdf"
    typ = tmp_path / "out.typ"
    code = main([
        str(usfm),
        str(pdf),
        "--typst-out",
        str(typ),
        "--font-dir",
        str(tmp_path / "missing"),
        "--no-compile",
    ])
    assert code == 0
    text = typ.read_text()
    assert "The Gospel According to John" in text
    assert "#woc[" in text
    assert "#footnote[" in text
    assert "#chapter-xrefs[" in text
    assert "#chapter-drop(" in text
    assert "Genesis 1:1" in text
    assert "#inscription[" in text
    assert "In the beginning was the Word" in text
    assert "Source Serif" not in text.split("Do not substitute Source Serif")[-1]


def test_parse_filters_to_john_only(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    books = parse_usfm_zip(usfm, book_names=["John"])
    assert [book["book"] for book in books] == ["John"]
    assert books[0]["title"] == "The Gospel According to John"


def test_words_of_christ_and_verse_inside_wj():
    segs = verse_segments_travel(
        r"\wj \v 39 “Come and see,”\wj* He replied.",
        "John",
        1,
    )
    assert segs[0][0] == 39
    assert "#woc[" in segs[0][2]
    assert "Come and see" in segs[0][2]
    assert "He replied" in segs[0][2]
    assert segs[0][2].index("#woc[") < segs[0][2].index("Come and see")


def test_words_of_christ_span_verses_same_paragraph():
    raw = (
        r'\v 5 Jesus answered, \wj “Truly, truly, I tell you. '
        r'\v 6 Flesh is born of flesh.”\wj*'
    )
    segs = verse_segments_travel(raw, "John", 3)
    assert segs[0][0] == 5
    assert segs[1][0] == 6
    assert "#woc[" in segs[0][2]
    assert "#woc[" in segs[1][2]
    assert "Flesh is born" in segs[1][2]


def test_footnote_inside_woc_keeps_note():
    raw = (
        r"\v 16 \wj For God so loved the world\f + \fr 3:16 \ft Or \fqa unique\f* Son.\wj*"
    )
    segs = verse_segments_travel(raw, "John", 3)
    body = segs[0][2]
    assert "#woc[" in body
    assert "#footnote[" in body
    assert "unique" in body


def test_xref_markup_strips_wrapping_parens():
    text = xref_markup(r"(\ref Genesis 1:1–2|GEN 1:1-2\ref*; \ref Hebrews 11:1–3|HEB 11:1-3\ref*)")
    assert text.startswith("#link(")
    assert "Genesis 1:1" in text
    assert not text.startswith("(")


def test_fqa_becomes_italic():
    markup = footnote_markup(r"+ \fr 1:5 \ft Or \fqa comprehended")
    assert "#emph[comprehended]" in markup


def test_chapter_open_drop_uses_only_first_verse():
    para = {
        "marker": "p",
        "raw": r"\v 1 In the beginning was the Word. \v 2 He was with God.",
    }
    lines = paragraph_markup(para, "John", 1, chapter_open=True)
    assert any("#chapter-drop(" in line for line in lines)
    assert any("#verse(" in line and "2" in line for line in lines)


def test_verse_number_is_boxed_in_preamble():
    preamble = travel_preamble()
    assert "#box[#vnum(n)#h(0.12em)]" in preamble


def test_generate_travel_typst_john_sample(tmp_path):
    usfm = write_sample_zip(tmp_path / "sample.zip")
    out = tmp_path / "john.typ"
    books = generate_travel_typst(usfm, out, books=("John",))
    text = out.read_text()
    assert books[0]["book"] == "John"
    assert text.count("#book-title") == 1
    assert "Genesis" not in text or "Genesis 1:1" in text
    assert "In the beginning." not in text
    assert "#set page(" in text
    assert "4.75in" in text or "4.75" in text


@pytest.mark.skipif(not USFM_ZIP.exists(), reason="official BSB USFM zip not present")
def test_real_usfm_john_preserves_corpus_text(tmp_path):
    out = tmp_path / "john.typ"
    books = generate_travel_typst(USFM_ZIP, out, books=("John",))
    assert [book["book"] for book in books] == ["John"]
    assert len(books[0]["chapters"]) == 21
    text = out.read_text(encoding="utf-8")
    assert "For God so loved the world" in text
    assert "In the beginning was the Word" in text
    assert "#woc[" in text
    assert text.count("#chapter-drop(") == 21
    assert "Source Serif 4" not in text
    assert "Lexend" not in text
